name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  geolocator: ^9.0.2
  sqflite: ^2.2.6
  path_provider: ^2.0.14
  http: ^0.13.5
  camera: ^0.10.3+2
  path: ^1.8.2
  flutter_spinkit: ^5.1.0
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.5
  sqlite3: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.6.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true